### ISSUE TITLE
Add feature flag to rely on the polling mechanism on all platforms

### ISSUE THREAD

**Issue by rklaehn** [dvc94ch/if-watch#4]
This might be a good short term solution until the added headers have made their way to musl. See #3 

But independent of this, this might also be a nice thing to have for obscure platforms.

The idea would be to have a feature flag that disables all the fancy stuff and just relies on the polling mechanism, which should be working on more platforms. This may or may not be a good idea, you decide.

**Comment by dvc94ch** [comment]
We already do this for all targets that aren't linux/windows. The problem in #3 is unfortunate, but it will be fixed for all current and future musl targets.
